// AuthenticationMiddleware.swift
// Auto-generated by swift-openapi-bootstrapper
// Security Scheme: BearerAuth

import Foundation
import OpenAPIRuntime
import HTTPTypes

public struct AuthenticationMiddleware: ClientMiddleware {
    public var apiKey: String

    public init(apiKey: String) {
        self.apiKey = apiKey
    }

    public func intercept(
        _ request: HTTPRequest,
        body: HTTPBody?,
        baseURL: URL,
        operationID: String,
        next: (HTTPRequest, HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
    ) async throws -> (HTTPResponse, HTTPBody?) {
        var request = request

        // API Key in Header Authentication
        if let httpFieldName = HTTPField.Name("authorization") {
            request.headerFields[httpFieldName] = apiKey
        }

        return try await next(request, body, baseURL)
    }
}
