// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Create access token
    ///
    /// Mint a short-lived access token from your API key. Call this from your server,
    /// then hand the returned `access_token` to a browser or mobile client. The client
    /// sends it as `Authorization: Bearer <access_token>` on TTS, STT and speech-to-speech
    /// requests. On
    /// WebSocket connections it can also go in the `api_key` query parameter. HTTP
    /// requests must use the header.
    ///
    /// A token works any number of times until it expires. It is accepted only on
    /// TTS, STT and speech-to-speech inference routes: `POST /waves/v1/stt/`, `WSS /waves/v1/stt/live`,
    /// `POST /waves/v1/tts`, `POST /waves/v1/tts/live`, `WSS /waves/v1/tts/live`, the
    /// dedicated Lightning v3.1 routes (`POST /waves/v1/lightning-v3.1/get_speech`,
    /// `POST /waves/v1/lightning-v3.1/stream`, `WSS /waves/v1/lightning-v3.1/get_speech/stream`),
    /// `WSS /waves/v1/s2s`, and the voice-listing routes (public catalog, no cloned
    /// voices). Treat any route not listed as unavailable to tokens. This endpoint,
    /// `POST /waves/v1/pulse/get_text`, voice cloning, pronunciation dictionaries,
    /// analytics and chat completions return `403` to a token.
    ///
    /// Requests made with a token are billed to the API key that minted it. Deleting
    /// that key invalidates its tokens. A token is valid only in the region that
    /// minted it. If your server and your users can be in different regions, mint and
    /// call through the same region-pinned hostname: `api.india.smallest.ai` (Mumbai) or
    /// `api.us.smallest.ai` (Oregon).
    ///
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/auth/token" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -d '{"ttl_seconds": 300}'
    /// ```
    ///
    /// See the [Authentication guide](/api-reference/token-based-authentication)
    /// for the end-to-end server and client flow.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/auth/token`.
    /// - Remark: Generated from `#/paths//waves/v1/auth/token/post(auth_create_access_token)`.
    func auth_create_access_token(_ input: Operations.auth_create_access_token.Input) async throws -> Operations.auth_create_access_token.Output
    /// Synthesize speech
    ///
    /// Synthesize speech from text in a single request. Pass `text` + `voice_id`, get back binary audio.
    ///
    /// Pick the model with the `model` body parameter: default `lightning_v3.1`, or `lightning_v3.1_pro` for the Pro pool. Other request parameters are identical across models.
    ///
    /// **Language behaviour on `lightning_v3.1_pro`:** pass `language: en` for UK + American accented English, pass `language: hi` for Indian accented English + Hindi (code-switching), or omit `language` to default to `en + hi` (mixed Indian + Western English coverage). Pro supports 31 languages total (10 Indic, 8 Asian & Middle Eastern, 13 European including Dutch and Swedish). Pass the matching ISO 639-1 code (e.g. `ta`, `de`, `ja`) with a Pro voice from that language, or use `auto` to route across all supported languages with any English or Hindi voice. See the [Lightning v3.1 Pro model card](/model-cards/text-to-speech/lightning-v-3-1-pro#supported-languages) for the full list. On `lightning_v3.1` the model accepts 20 language codes (10 European + 10 Indic) plus `auto`; the trained voice catalog covers 12 of those directly.
    ///
    /// ## When to use this
    ///
    /// - **Use this** for short utterances you can render before playback (notifications, prompts, batch jobs, audio file generation).
    /// - **Use `/waves/v1/tts/live`** when you want playback to start before the full audio is ready (long passages, latency-sensitive apps).
    /// - **Use `/waves/v1/tts/live`** (WebSocket) when text arrives incrementally (LLM token streams, live captioning).
    ///
    /// ## Key features
    ///
    /// - 44 kHz natural, expressive synthesis
    /// - Model selectable per request via `model` body parameter
    /// - Cloned voice IDs (`voice_*`) work on `lightning_v3.1` — same param as catalog voices
    /// - 20 accepted language codes on `lightning_v3.1` (12 with trained voices, 8 additional routed via English/Hindi voices). On `lightning_v3.1_pro`: 31 languages with dedicated voices (10 Indic, 8 Asian & Middle Eastern, 13 European); `language: en` → UK + American accented English; `language: hi` → Indian accented English + Hindi; omit `language` → defaults to `en + hi`. Both models accept `language: auto` for cross-language routing.
    /// - Output formats: `pcm`, `mp3`, `wav`, `ulaw`, `alaw`
    /// - Sample rates: 8 kHz – 44.1 kHz
    /// - Speed: 0.5× – 2×
    /// - Per-call pronunciation dictionaries via `pronunciation_dicts`
    ///
    /// ## Examples
    ///
    /// **cURL — Lightning v3.1 (default)**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/tts" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -H "Accept: audio/wav" \
    ///   -d '{
    ///     "text": "Hello from Waves TTS.",
    ///     "voice_id": "magnus",
    ///     "sample_rate": 24000,
    ///     "output_format": "wav"
    ///   }' --output speech.wav
    /// ```
    ///
    /// **cURL — Lightning v3.1 Pro (omit `language` → defaults to `en + hi`)**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/tts" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -H "Accept: audio/wav" \
    ///   -d '{
    ///     "text": "Hello from the Lightning v3.1 Pro pool.",
    ///     "voice_id": "meher",
    ///     "model": "lightning_v3.1_pro",
    ///     "sample_rate": 24000,
    ///     "output_format": "wav"
    ///   }' --output speech.wav
    /// ```
    ///
    /// **cURL — Lightning v3.1 Pro with explicit `language: en` (UK + American accented English)**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/tts" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -H "Accept: audio/wav" \
    ///   -d '{
    ///     "text": "Good morning, this is a Pro voice speaking.",
    ///     "voice_id": "meher",
    ///     "model": "lightning_v3.1_pro",
    ///     "language": "en",
    ///     "sample_rate": 24000,
    ///     "output_format": "wav"
    ///   }' --output speech.wav
    /// ```
    ///
    /// **cURL — Lightning v3.1 Pro with explicit `language: hi` (Indian accented English + Hindi)**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/tts" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -H "Accept: audio/wav" \
    ///   -d '{
    ///     "text": "Namaste, this is an Indian-accented Pro voice.",
    ///     "voice_id": "meher",
    ///     "model": "lightning_v3.1_pro",
    ///     "language": "hi",
    ///     "sample_rate": 24000,
    ///     "output_format": "wav"
    ///   }' --output speech.wav
    /// ```
    ///
    /// ## Common gotchas
    ///
    /// - **Set `Accept: audio/wav`.** Omitting it can return an empty or unplayable response.
    /// - **Pair voice IDs with the right model.** Voice catalogs differ between `lightning_v3.1` and `lightning_v3.1_pro`. The API does not reject mismatched pairings, but using a Pro-only `voice_id` with `model=lightning_v3.1` (or omitting `model`) can return wrong or hallucinated audio. Pair Pro voices with `model=lightning_v3.1_pro`; standard catalog voices with `model=lightning_v3.1` (the default).
    /// - **Cloned voices** (`voice_*`) work with the pool they were cloned onto. The voice-cloning API accepts `model: lightning-v3.1` (default) or `lightning-v3.1-pro`; pair the resulting `voice_id` with the matching TTS `model` (`lightning_v3.1` or `lightning_v3.1_pro`). Check the clone's `modelIds` if unsure.
    /// - **44.1 kHz output** is supported but most playback environments are happy with 24 kHz — drop the sample rate if bandwidth matters.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/tts`.
    /// - Remark: Generated from `#/paths//waves/v1/tts/post(textToSpeech_synthesizeSpeech)`.
    func textToSpeech_synthesizeSpeech(_ input: Operations.textToSpeech_synthesizeSpeech.Input) async throws -> Operations.textToSpeech_synthesizeSpeech.Output
    /// Stream speech (SSE)
    ///
    /// Synthesize speech and stream the audio back over Server-Sent Events. Same body as `/waves/v1/tts` — the only difference is the response is a stream of base64-encoded PCM chunks instead of one binary blob.
    ///
    /// Pick the model with the `model` body parameter, same as the sync route.
    ///
    /// <Note>
    ///   **The same URL serves the WebSocket endpoint.** `wss://api.smallest.ai/waves/v1/tts/live` accepts a WebSocket upgrade for streaming-text scenarios (LLM token streams, live captioning). The HTTP `POST` documented on this page returns SSE; use `wss://` to use the WebSocket protocol instead. See the [WebSocket reference](/models/text-to-speech/streaming).
    /// </Note>
    ///
    /// ## When to use this
    ///
    /// - **Use this** when you want playback to start before synthesis is complete — long passages, latency-sensitive UI, live narration.
    /// - **Use sync `/waves/v1/tts`** when total latency doesn't matter and you'd rather get one buffer.
    /// - **Use `/waves/v1/tts/live`** (WebSocket) when the *text* arrives incrementally (LLM token stream). SSE assumes you have the full text up front.
    ///
    /// ## How it works
    ///
    /// 1. POST your text + voice settings — same payload as `/waves/v1/tts`, plus optional `model`.
    /// 2. The response is `Content-Type: text/event-stream`. Each chunk frame is `event: audio\n` followed by `data: {"audio": "<base64-pcm>", "done": false, "status": "206"}\n\n`.
    /// 3. Decode each chunk's `audio` field with base64 and feed the PCM bytes to your audio pipeline (browser `MediaSource`, ffmpeg pipe, raw PCM player, etc.).
    /// 4. A final `data: {"status": "200", "done": true}\n\n` frame marks end of stream. Detect the terminator with `done == true`; every chunk frame also carries `done: false`, so `"done" in msg` matches every frame.
    ///
    /// ## Examples
    ///
    /// **cURL**
    /// ```bash
    /// curl -N -X POST "https://api.smallest.ai/waves/v1/tts/live" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -d '{
    ///     "text": "Streaming this paragraph chunk by chunk so playback can start sooner.",
    ///     "voice_id": "magnus",
    ///     "sample_rate": 24000,
    ///     "output_format": "pcm"
    ///   }'
    /// ```
    ///
    /// ## Common gotchas
    ///
    /// - **Use a streaming-friendly client.** `curl -N`, Python `iter_lines`, or a `fetch` `ReadableStream` reader. Buffering clients will hide the latency win.
    /// - **Audio is base64 inside the event payload**, not the raw event bytes. Decode the `data.audio` field per event.
    /// - **`output_format=pcm`** gives the lowest overhead for streaming playback. `wav`/`mp3` work but add per-chunk framing bytes.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/tts/live`.
    /// - Remark: Generated from `#/paths//waves/v1/tts/live/post(textToSpeech_synthesizeSpeechSse)`.
    func textToSpeech_synthesizeSpeechSse(_ input: Operations.textToSpeech_synthesizeSpeechSse.Input) async throws -> Operations.textToSpeech_synthesizeSpeechSse.Output
    /// Get voices for a pool
    ///
    /// Return the voice catalog for the chosen Lightning v3.1 pool. Two pools:
    ///
    /// - `lightning-v3.1` — the Standard catalog. Supports voice cloning; 20 language codes.
    /// - `lightning-v3.1-pro` — the Pro catalog. Curated set across American, British, and Indian accents plus 29 additional languages. Same latency and concurrency as Standard, on dedicated inference.
    ///
    /// The endpoint is pool-scoped: `/waves/v1/lightning-v3.1/get_voices` returns Standard voices only; `/waves/v1/lightning-v3.1-pro/get_voices` returns Pro voices only. Call one or both depending on which pool you plan to use.
    ///
    /// Each voice carries tags (`language`, `accent`, `gender`, `age`, `emotions`, `usecases`). Filter client-side to find the voices that match a target language, accent, or use case. Pass the returned `voiceId` as `voice_id` on the unified [`POST /waves/v1/tts`](/api-reference/models/text-to-speech/synthesize-speech) route, together with `"model": "lightning_v3.1"` (Standard) or `"model": "lightning_v3.1_pro"` (Pro).
    ///
    /// For the canonical per-language voice list (with previews and recommended pairings), see the [Lightning v3.1](/model-cards/text-to-speech/lightning-v-3-1) and [Lightning v3.1 Pro](/model-cards/text-to-speech/lightning-v-3-1-pro) model cards.
    ///
    ///
    /// - Remark: HTTP `GET /waves/v1/{model}/get_voices`.
    /// - Remark: Generated from `#/paths//waves/v1/{model}/get_voices/get(voices_getWavesVoices)`.
    func voices_getWavesVoices(_ input: Operations.voices_getWavesVoices.Input) async throws -> Operations.voices_getWavesVoices.Output
    /// List Voice Clones
    ///
    /// Retrieve all voice clones in your organization.
    ///
    ///
    /// - Remark: HTTP `GET /waves/v1/voice-cloning`.
    /// - Remark: Generated from `#/paths//waves/v1/voice-cloning/get(voiceCloning_listVoiceClones)`.
    func voiceCloning_listVoiceClones(_ input: Operations.voiceCloning_listVoiceClones.Input) async throws -> Operations.voiceCloning_listVoiceClones.Output
    /// Create a Voice Clone
    ///
    /// Create an instant voice clone in a single call. Defaults to `lightning-v3.1`.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/voice-cloning`.
    /// - Remark: Generated from `#/paths//waves/v1/voice-cloning/post(voiceCloning_createVoiceClone)`.
    func voiceCloning_createVoiceClone(_ input: Operations.voiceCloning_createVoiceClone.Input) async throws -> Operations.voiceCloning_createVoiceClone.Output
    /// List
    ///
    /// Retrieve all pronunciation dictionaries for the authenticated user
    ///
    /// - Remark: HTTP `GET /waves/v1/pronunciation-dicts`.
    /// - Remark: Generated from `#/paths//waves/v1/pronunciation-dicts/get(pronunciationDictionaries_getPronunciationDicts)`.
    func pronunciationDictionaries_getPronunciationDicts(_ input: Operations.pronunciationDictionaries_getPronunciationDicts.Input) async throws -> Operations.pronunciationDictionaries_getPronunciationDicts.Output
    /// Create
    ///
    /// Create a new pronunciation dictionary for the authenticated user
    ///
    /// - Remark: HTTP `POST /waves/v1/pronunciation-dicts`.
    /// - Remark: Generated from `#/paths//waves/v1/pronunciation-dicts/post(pronunciationDictionaries_createPronunciationDict)`.
    func pronunciationDictionaries_createPronunciationDict(_ input: Operations.pronunciationDictionaries_createPronunciationDict.Input) async throws -> Operations.pronunciationDictionaries_createPronunciationDict.Output
    /// Update
    ///
    /// Update an existing pronunciation dictionary for the authenticated user
    ///
    /// - Remark: HTTP `PUT /waves/v1/pronunciation-dicts`.
    /// - Remark: Generated from `#/paths//waves/v1/pronunciation-dicts/put(pronunciationDictionaries_updatePronunciationDict)`.
    func pronunciationDictionaries_updatePronunciationDict(_ input: Operations.pronunciationDictionaries_updatePronunciationDict.Input) async throws -> Operations.pronunciationDictionaries_updatePronunciationDict.Output
    /// Delete
    ///
    /// Delete an existing pronunciation dictionary for the authenticated user
    ///
    /// - Remark: HTTP `DELETE /waves/v1/pronunciation-dicts`.
    /// - Remark: Generated from `#/paths//waves/v1/pronunciation-dicts/delete(pronunciationDictionaries_deletePronunciationDict)`.
    func pronunciationDictionaries_deletePronunciationDict(_ input: Operations.pronunciationDictionaries_deletePronunciationDict.Input) async throws -> Operations.pronunciationDictionaries_deletePronunciationDict.Output
    /// Transcribe (Pre-recorded)
    ///
    /// Transcribe an audio file. The model is chosen via `?model=`:
    ///
    /// - `?model=pulse-pro`: English-only, leaderboard-ranked accuracy. Raw bytes only; pass `webhook_url` to receive transcription asynchronously on long files.
    /// - `?model=pulse`: multilingual transcription (21 streaming + 12 pre-recorded languages), supports both raw bytes and audio-by-URL.
    ///
    /// ## When to use this
    ///
    /// Use this endpoint when you have a complete audio file (call recording, voicemail, podcast episode) and want the transcript back in one response. For live transcription as audio arrives, use the realtime WebSocket endpoint (`WS /waves/v1/stt/live?model=pulse`).
    ///
    /// Pulse Pro is HTTP-only.
    ///
    /// ## Input methods
    ///
    /// - **Raw bytes**: `Content-Type: application/octet-stream` with the audio in the body. All knobs are query parameters.
    /// - **URL (`?model=pulse` only)**: `Content-Type: application/json` with `{"url": "..."}` in the body.
    ///
    /// ## Examples
    ///
    /// **cURL**: Pulse Pro, sync
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/stt/?model=pulse-pro&language=en&word_timestamps=true" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/octet-stream" \
    ///   --data-binary "@./call.wav"
    /// ```
    ///
    /// **cURL**: Pulse Pro, async via webhook
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/stt/?model=pulse-pro&language=en&webhook_url=https://your.app/cb" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/octet-stream" \
    ///   --data-binary "@./call.wav"
    /// ```
    /// Returns `200 { "status": "processing", "request_id": "..." }` immediately. The webhook receives the full transcription when ready.
    ///
    /// **cURL**: Pulse, audio-by-URL
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/stt/?model=pulse&language=en" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -d '{"url": "https://your-bucket.s3.amazonaws.com/call.wav"}'
    /// ```
    ///
    /// **Python**
    /// ```python
    /// import requests
    ///
    /// with open("./call.wav", "rb") as f:
    ///     audio = f.read()
    ///
    /// r = requests.post(
    ///     "https://api.smallest.ai/waves/v1/stt/",
    ///     params={"model": "pulse-pro", "language": "en", "word_timestamps": "true"},
    ///     headers={"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/octet-stream"},
    ///     data=audio,
    /// )
    /// r.raise_for_status()
    /// print(r.json()["transcription"])
    /// ```
    ///
    /// **JavaScript / TypeScript**
    /// ```typescript
    /// import { readFileSync } from "node:fs";
    ///
    /// const audio = readFileSync("./call.wav");
    /// const params = new URLSearchParams({ model: "pulse-pro", language: "en", word_timestamps: "true" });
    ///
    /// const res = await fetch(`https://api.smallest.ai/waves/v1/stt/?${params}`, {
    ///   method: "POST",
    ///   headers: { Authorization: `Bearer ${process.env.SMALLEST_API_KEY}`, "Content-Type": "application/octet-stream" },
    ///   body: audio,
    /// });
    /// console.log((await res.json()).transcription);
    /// ```
    ///
    /// ## Common gotchas
    ///
    /// - **`model` is required.** Missing or invalid values return `400` with an enum-validation error.
    /// - **Pulse Pro is English only.** Pass `language=en`. Any other value returns `400 invalid_enum_value` (`Expected 'en', received '<x>'`).
    /// - **Pulse Pro does not support audio-by-URL.** Send raw bytes or use `?model=pulse` for the URL flow.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/stt/`.
    /// - Remark: Generated from `#/paths//waves/v1/stt//post(speechToText_transcribe)`.
    func speechToText_transcribe(_ input: Operations.speechToText_transcribe.Input) async throws -> Operations.speechToText_transcribe.Output
    /// Chat Completions (Electron)
    ///
    /// Generate a chat completion with Electron. OpenAI-compatible
    /// request/response shape — point any OpenAI SDK at
    /// `https://api.smallest.ai/waves/v1` and it just works.
    ///
    /// Set `stream: true` to receive tokens via Server-Sent Events. With
    /// `stream_options: { include_usage: true }`, the final SSE chunk
    /// carries the `usage` block so token accounting is exact even on
    /// client disconnects.
    ///
    /// Tool calling follows OpenAI's `tools` array convention. When you
    /// provide a voice-agent-style system prompt, Electron emits a short
    /// filler phrase in the assistant message `content` field alongside
    /// `tool_calls` — see the [Tool Calling guide](/models/llm/tool-function-calling)
    /// for the voice-agent pattern.
    ///
    /// ## Examples
    ///
    /// **cURL**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/chat/completions" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -d '{
    ///     "model": "electron",
    ///     "messages": [
    ///       {"role": "user", "content": "Write one sentence about why the sky is blue."}
    ///     ]
    ///   }'
    /// ```
    ///
    /// **Python** (`pip install openai`)
    /// ```python
    /// import os
    /// from openai import OpenAI
    ///
    /// client = OpenAI(
    ///     base_url="https://api.smallest.ai/waves/v1",
    ///     api_key=os.environ["SMALLEST_API_KEY"],
    /// )
    ///
    /// response = client.chat.completions.create(
    ///     model="electron",
    ///     messages=[
    ///         {"role": "user", "content": "Write one sentence about why the sky is blue."}
    ///     ],
    /// )
    ///
    /// print(response.choices[0].message.content)
    /// ```
    ///
    /// **JavaScript / TypeScript** (`npm install openai`)
    /// ```typescript
    /// import OpenAI from "openai";
    ///
    /// const client = new OpenAI({
    ///   baseURL: "https://api.smallest.ai/waves/v1",
    ///   apiKey: process.env.SMALLEST_API_KEY,
    /// });
    ///
    /// const response = await client.chat.completions.create({
    ///   model: "electron",
    ///   messages: [
    ///     { role: "user", content: "Write one sentence about why the sky is blue." },
    ///   ],
    /// });
    ///
    /// console.log(response.choices[0].message.content);
    /// ```
    ///
    /// **Streaming with usage** (Python)
    /// ```python
    /// stream = client.chat.completions.create(
    ///     model="electron",
    ///     messages=[{"role": "user", "content": "Tell me a one-sentence fun fact."}],
    ///     stream=True,
    ///     stream_options={"include_usage": True},
    /// )
    /// for chunk in stream:
    ///     if chunk.choices and chunk.choices[0].delta.content:
    ///         print(chunk.choices[0].delta.content, end="", flush=True)
    ///     if chunk.usage:
    ///         print(f"\n\nTokens: {chunk.usage.total_tokens}")
    /// ```
    ///
    /// ## Common gotchas
    ///
    /// - **Base URL is `/waves/v1`**, not `/v1`. The OpenAI SDK appends `/chat/completions` for you.
    /// - **`stream_options.include_usage: true`** is required for exact token accounting on streaming calls — the final SSE chunk carries the `usage` block.
    /// - **`n > 1` and `prompt_logprobs` are rejected.** Use multiple requests if you need parallel completions.
    /// - **Auth header is `Authorization: Bearer $SMALLEST_API_KEY`** — get the key from the [Smallest AI Console](https://app.smallest.ai/dashboard/api-keys).
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/chat/completions`.
    /// - Remark: Generated from `#/paths//waves/v1/chat/completions/post(electron_complete)`.
    func electron_complete(_ input: Operations.electron_complete.Input) async throws -> Operations.electron_complete.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Create access token
    ///
    /// Mint a short-lived access token from your API key. Call this from your server,
    /// then hand the returned `access_token` to a browser or mobile client. The client
    /// sends it as `Authorization: Bearer <access_token>` on TTS, STT and speech-to-speech
    /// requests. On
    /// WebSocket connections it can also go in the `api_key` query parameter. HTTP
    /// requests must use the header.
    ///
    /// A token works any number of times until it expires. It is accepted only on
    /// TTS, STT and speech-to-speech inference routes: `POST /waves/v1/stt/`, `WSS /waves/v1/stt/live`,
    /// `POST /waves/v1/tts`, `POST /waves/v1/tts/live`, `WSS /waves/v1/tts/live`, the
    /// dedicated Lightning v3.1 routes (`POST /waves/v1/lightning-v3.1/get_speech`,
    /// `POST /waves/v1/lightning-v3.1/stream`, `WSS /waves/v1/lightning-v3.1/get_speech/stream`),
    /// `WSS /waves/v1/s2s`, and the voice-listing routes (public catalog, no cloned
    /// voices). Treat any route not listed as unavailable to tokens. This endpoint,
    /// `POST /waves/v1/pulse/get_text`, voice cloning, pronunciation dictionaries,
    /// analytics and chat completions return `403` to a token.
    ///
    /// Requests made with a token are billed to the API key that minted it. Deleting
    /// that key invalidates its tokens. A token is valid only in the region that
    /// minted it. If your server and your users can be in different regions, mint and
    /// call through the same region-pinned hostname: `api.india.smallest.ai` (Mumbai) or
    /// `api.us.smallest.ai` (Oregon).
    ///
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/auth/token" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -d '{"ttl_seconds": 300}'
    /// ```
    ///
    /// See the [Authentication guide](/api-reference/token-based-authentication)
    /// for the end-to-end server and client flow.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/auth/token`.
    /// - Remark: Generated from `#/paths//waves/v1/auth/token/post(auth_create_access_token)`.
    public func auth_create_access_token(
        headers: Operations.auth_create_access_token.Input.Headers = .init(),
        body: Operations.auth_create_access_token.Input.Body? = nil
    ) async throws -> Operations.auth_create_access_token.Output {
        try await auth_create_access_token(Operations.auth_create_access_token.Input(
            headers: headers,
            body: body
        ))
    }
    /// Synthesize speech
    ///
    /// Synthesize speech from text in a single request. Pass `text` + `voice_id`, get back binary audio.
    ///
    /// Pick the model with the `model` body parameter: default `lightning_v3.1`, or `lightning_v3.1_pro` for the Pro pool. Other request parameters are identical across models.
    ///
    /// **Language behaviour on `lightning_v3.1_pro`:** pass `language: en` for UK + American accented English, pass `language: hi` for Indian accented English + Hindi (code-switching), or omit `language` to default to `en + hi` (mixed Indian + Western English coverage). Pro supports 31 languages total (10 Indic, 8 Asian & Middle Eastern, 13 European including Dutch and Swedish). Pass the matching ISO 639-1 code (e.g. `ta`, `de`, `ja`) with a Pro voice from that language, or use `auto` to route across all supported languages with any English or Hindi voice. See the [Lightning v3.1 Pro model card](/model-cards/text-to-speech/lightning-v-3-1-pro#supported-languages) for the full list. On `lightning_v3.1` the model accepts 20 language codes (10 European + 10 Indic) plus `auto`; the trained voice catalog covers 12 of those directly.
    ///
    /// ## When to use this
    ///
    /// - **Use this** for short utterances you can render before playback (notifications, prompts, batch jobs, audio file generation).
    /// - **Use `/waves/v1/tts/live`** when you want playback to start before the full audio is ready (long passages, latency-sensitive apps).
    /// - **Use `/waves/v1/tts/live`** (WebSocket) when text arrives incrementally (LLM token streams, live captioning).
    ///
    /// ## Key features
    ///
    /// - 44 kHz natural, expressive synthesis
    /// - Model selectable per request via `model` body parameter
    /// - Cloned voice IDs (`voice_*`) work on `lightning_v3.1` — same param as catalog voices
    /// - 20 accepted language codes on `lightning_v3.1` (12 with trained voices, 8 additional routed via English/Hindi voices). On `lightning_v3.1_pro`: 31 languages with dedicated voices (10 Indic, 8 Asian & Middle Eastern, 13 European); `language: en` → UK + American accented English; `language: hi` → Indian accented English + Hindi; omit `language` → defaults to `en + hi`. Both models accept `language: auto` for cross-language routing.
    /// - Output formats: `pcm`, `mp3`, `wav`, `ulaw`, `alaw`
    /// - Sample rates: 8 kHz – 44.1 kHz
    /// - Speed: 0.5× – 2×
    /// - Per-call pronunciation dictionaries via `pronunciation_dicts`
    ///
    /// ## Examples
    ///
    /// **cURL — Lightning v3.1 (default)**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/tts" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -H "Accept: audio/wav" \
    ///   -d '{
    ///     "text": "Hello from Waves TTS.",
    ///     "voice_id": "magnus",
    ///     "sample_rate": 24000,
    ///     "output_format": "wav"
    ///   }' --output speech.wav
    /// ```
    ///
    /// **cURL — Lightning v3.1 Pro (omit `language` → defaults to `en + hi`)**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/tts" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -H "Accept: audio/wav" \
    ///   -d '{
    ///     "text": "Hello from the Lightning v3.1 Pro pool.",
    ///     "voice_id": "meher",
    ///     "model": "lightning_v3.1_pro",
    ///     "sample_rate": 24000,
    ///     "output_format": "wav"
    ///   }' --output speech.wav
    /// ```
    ///
    /// **cURL — Lightning v3.1 Pro with explicit `language: en` (UK + American accented English)**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/tts" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -H "Accept: audio/wav" \
    ///   -d '{
    ///     "text": "Good morning, this is a Pro voice speaking.",
    ///     "voice_id": "meher",
    ///     "model": "lightning_v3.1_pro",
    ///     "language": "en",
    ///     "sample_rate": 24000,
    ///     "output_format": "wav"
    ///   }' --output speech.wav
    /// ```
    ///
    /// **cURL — Lightning v3.1 Pro with explicit `language: hi` (Indian accented English + Hindi)**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/tts" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -H "Accept: audio/wav" \
    ///   -d '{
    ///     "text": "Namaste, this is an Indian-accented Pro voice.",
    ///     "voice_id": "meher",
    ///     "model": "lightning_v3.1_pro",
    ///     "language": "hi",
    ///     "sample_rate": 24000,
    ///     "output_format": "wav"
    ///   }' --output speech.wav
    /// ```
    ///
    /// ## Common gotchas
    ///
    /// - **Set `Accept: audio/wav`.** Omitting it can return an empty or unplayable response.
    /// - **Pair voice IDs with the right model.** Voice catalogs differ between `lightning_v3.1` and `lightning_v3.1_pro`. The API does not reject mismatched pairings, but using a Pro-only `voice_id` with `model=lightning_v3.1` (or omitting `model`) can return wrong or hallucinated audio. Pair Pro voices with `model=lightning_v3.1_pro`; standard catalog voices with `model=lightning_v3.1` (the default).
    /// - **Cloned voices** (`voice_*`) work with the pool they were cloned onto. The voice-cloning API accepts `model: lightning-v3.1` (default) or `lightning-v3.1-pro`; pair the resulting `voice_id` with the matching TTS `model` (`lightning_v3.1` or `lightning_v3.1_pro`). Check the clone's `modelIds` if unsure.
    /// - **44.1 kHz output** is supported but most playback environments are happy with 24 kHz — drop the sample rate if bandwidth matters.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/tts`.
    /// - Remark: Generated from `#/paths//waves/v1/tts/post(textToSpeech_synthesizeSpeech)`.
    public func textToSpeech_synthesizeSpeech(
        headers: Operations.textToSpeech_synthesizeSpeech.Input.Headers = .init(),
        body: Operations.textToSpeech_synthesizeSpeech.Input.Body? = nil
    ) async throws -> Operations.textToSpeech_synthesizeSpeech.Output {
        try await textToSpeech_synthesizeSpeech(Operations.textToSpeech_synthesizeSpeech.Input(
            headers: headers,
            body: body
        ))
    }
    /// Stream speech (SSE)
    ///
    /// Synthesize speech and stream the audio back over Server-Sent Events. Same body as `/waves/v1/tts` — the only difference is the response is a stream of base64-encoded PCM chunks instead of one binary blob.
    ///
    /// Pick the model with the `model` body parameter, same as the sync route.
    ///
    /// <Note>
    ///   **The same URL serves the WebSocket endpoint.** `wss://api.smallest.ai/waves/v1/tts/live` accepts a WebSocket upgrade for streaming-text scenarios (LLM token streams, live captioning). The HTTP `POST` documented on this page returns SSE; use `wss://` to use the WebSocket protocol instead. See the [WebSocket reference](/models/text-to-speech/streaming).
    /// </Note>
    ///
    /// ## When to use this
    ///
    /// - **Use this** when you want playback to start before synthesis is complete — long passages, latency-sensitive UI, live narration.
    /// - **Use sync `/waves/v1/tts`** when total latency doesn't matter and you'd rather get one buffer.
    /// - **Use `/waves/v1/tts/live`** (WebSocket) when the *text* arrives incrementally (LLM token stream). SSE assumes you have the full text up front.
    ///
    /// ## How it works
    ///
    /// 1. POST your text + voice settings — same payload as `/waves/v1/tts`, plus optional `model`.
    /// 2. The response is `Content-Type: text/event-stream`. Each chunk frame is `event: audio\n` followed by `data: {"audio": "<base64-pcm>", "done": false, "status": "206"}\n\n`.
    /// 3. Decode each chunk's `audio` field with base64 and feed the PCM bytes to your audio pipeline (browser `MediaSource`, ffmpeg pipe, raw PCM player, etc.).
    /// 4. A final `data: {"status": "200", "done": true}\n\n` frame marks end of stream. Detect the terminator with `done == true`; every chunk frame also carries `done: false`, so `"done" in msg` matches every frame.
    ///
    /// ## Examples
    ///
    /// **cURL**
    /// ```bash
    /// curl -N -X POST "https://api.smallest.ai/waves/v1/tts/live" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -d '{
    ///     "text": "Streaming this paragraph chunk by chunk so playback can start sooner.",
    ///     "voice_id": "magnus",
    ///     "sample_rate": 24000,
    ///     "output_format": "pcm"
    ///   }'
    /// ```
    ///
    /// ## Common gotchas
    ///
    /// - **Use a streaming-friendly client.** `curl -N`, Python `iter_lines`, or a `fetch` `ReadableStream` reader. Buffering clients will hide the latency win.
    /// - **Audio is base64 inside the event payload**, not the raw event bytes. Decode the `data.audio` field per event.
    /// - **`output_format=pcm`** gives the lowest overhead for streaming playback. `wav`/`mp3` work but add per-chunk framing bytes.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/tts/live`.
    /// - Remark: Generated from `#/paths//waves/v1/tts/live/post(textToSpeech_synthesizeSpeechSse)`.
    public func textToSpeech_synthesizeSpeechSse(
        headers: Operations.textToSpeech_synthesizeSpeechSse.Input.Headers = .init(),
        body: Operations.textToSpeech_synthesizeSpeechSse.Input.Body? = nil
    ) async throws -> Operations.textToSpeech_synthesizeSpeechSse.Output {
        try await textToSpeech_synthesizeSpeechSse(Operations.textToSpeech_synthesizeSpeechSse.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get voices for a pool
    ///
    /// Return the voice catalog for the chosen Lightning v3.1 pool. Two pools:
    ///
    /// - `lightning-v3.1` — the Standard catalog. Supports voice cloning; 20 language codes.
    /// - `lightning-v3.1-pro` — the Pro catalog. Curated set across American, British, and Indian accents plus 29 additional languages. Same latency and concurrency as Standard, on dedicated inference.
    ///
    /// The endpoint is pool-scoped: `/waves/v1/lightning-v3.1/get_voices` returns Standard voices only; `/waves/v1/lightning-v3.1-pro/get_voices` returns Pro voices only. Call one or both depending on which pool you plan to use.
    ///
    /// Each voice carries tags (`language`, `accent`, `gender`, `age`, `emotions`, `usecases`). Filter client-side to find the voices that match a target language, accent, or use case. Pass the returned `voiceId` as `voice_id` on the unified [`POST /waves/v1/tts`](/api-reference/models/text-to-speech/synthesize-speech) route, together with `"model": "lightning_v3.1"` (Standard) or `"model": "lightning_v3.1_pro"` (Pro).
    ///
    /// For the canonical per-language voice list (with previews and recommended pairings), see the [Lightning v3.1](/model-cards/text-to-speech/lightning-v-3-1) and [Lightning v3.1 Pro](/model-cards/text-to-speech/lightning-v-3-1-pro) model cards.
    ///
    ///
    /// - Remark: HTTP `GET /waves/v1/{model}/get_voices`.
    /// - Remark: Generated from `#/paths//waves/v1/{model}/get_voices/get(voices_getWavesVoices)`.
    public func voices_getWavesVoices(
        path: Operations.voices_getWavesVoices.Input.Path,
        headers: Operations.voices_getWavesVoices.Input.Headers = .init()
    ) async throws -> Operations.voices_getWavesVoices.Output {
        try await voices_getWavesVoices(Operations.voices_getWavesVoices.Input(
            path: path,
            headers: headers
        ))
    }
    /// List Voice Clones
    ///
    /// Retrieve all voice clones in your organization.
    ///
    ///
    /// - Remark: HTTP `GET /waves/v1/voice-cloning`.
    /// - Remark: Generated from `#/paths//waves/v1/voice-cloning/get(voiceCloning_listVoiceClones)`.
    public func voiceCloning_listVoiceClones(headers: Operations.voiceCloning_listVoiceClones.Input.Headers = .init()) async throws -> Operations.voiceCloning_listVoiceClones.Output {
        try await voiceCloning_listVoiceClones(Operations.voiceCloning_listVoiceClones.Input(headers: headers))
    }
    /// Create a Voice Clone
    ///
    /// Create an instant voice clone in a single call. Defaults to `lightning-v3.1`.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/voice-cloning`.
    /// - Remark: Generated from `#/paths//waves/v1/voice-cloning/post(voiceCloning_createVoiceClone)`.
    public func voiceCloning_createVoiceClone(
        headers: Operations.voiceCloning_createVoiceClone.Input.Headers = .init(),
        body: Operations.voiceCloning_createVoiceClone.Input.Body
    ) async throws -> Operations.voiceCloning_createVoiceClone.Output {
        try await voiceCloning_createVoiceClone(Operations.voiceCloning_createVoiceClone.Input(
            headers: headers,
            body: body
        ))
    }
    /// List
    ///
    /// Retrieve all pronunciation dictionaries for the authenticated user
    ///
    /// - Remark: HTTP `GET /waves/v1/pronunciation-dicts`.
    /// - Remark: Generated from `#/paths//waves/v1/pronunciation-dicts/get(pronunciationDictionaries_getPronunciationDicts)`.
    public func pronunciationDictionaries_getPronunciationDicts(headers: Operations.pronunciationDictionaries_getPronunciationDicts.Input.Headers = .init()) async throws -> Operations.pronunciationDictionaries_getPronunciationDicts.Output {
        try await pronunciationDictionaries_getPronunciationDicts(Operations.pronunciationDictionaries_getPronunciationDicts.Input(headers: headers))
    }
    /// Create
    ///
    /// Create a new pronunciation dictionary for the authenticated user
    ///
    /// - Remark: HTTP `POST /waves/v1/pronunciation-dicts`.
    /// - Remark: Generated from `#/paths//waves/v1/pronunciation-dicts/post(pronunciationDictionaries_createPronunciationDict)`.
    public func pronunciationDictionaries_createPronunciationDict(
        headers: Operations.pronunciationDictionaries_createPronunciationDict.Input.Headers = .init(),
        body: Operations.pronunciationDictionaries_createPronunciationDict.Input.Body? = nil
    ) async throws -> Operations.pronunciationDictionaries_createPronunciationDict.Output {
        try await pronunciationDictionaries_createPronunciationDict(Operations.pronunciationDictionaries_createPronunciationDict.Input(
            headers: headers,
            body: body
        ))
    }
    /// Update
    ///
    /// Update an existing pronunciation dictionary for the authenticated user
    ///
    /// - Remark: HTTP `PUT /waves/v1/pronunciation-dicts`.
    /// - Remark: Generated from `#/paths//waves/v1/pronunciation-dicts/put(pronunciationDictionaries_updatePronunciationDict)`.
    public func pronunciationDictionaries_updatePronunciationDict(
        headers: Operations.pronunciationDictionaries_updatePronunciationDict.Input.Headers = .init(),
        body: Operations.pronunciationDictionaries_updatePronunciationDict.Input.Body? = nil
    ) async throws -> Operations.pronunciationDictionaries_updatePronunciationDict.Output {
        try await pronunciationDictionaries_updatePronunciationDict(Operations.pronunciationDictionaries_updatePronunciationDict.Input(
            headers: headers,
            body: body
        ))
    }
    /// Delete
    ///
    /// Delete an existing pronunciation dictionary for the authenticated user
    ///
    /// - Remark: HTTP `DELETE /waves/v1/pronunciation-dicts`.
    /// - Remark: Generated from `#/paths//waves/v1/pronunciation-dicts/delete(pronunciationDictionaries_deletePronunciationDict)`.
    public func pronunciationDictionaries_deletePronunciationDict(
        headers: Operations.pronunciationDictionaries_deletePronunciationDict.Input.Headers = .init(),
        body: Operations.pronunciationDictionaries_deletePronunciationDict.Input.Body? = nil
    ) async throws -> Operations.pronunciationDictionaries_deletePronunciationDict.Output {
        try await pronunciationDictionaries_deletePronunciationDict(Operations.pronunciationDictionaries_deletePronunciationDict.Input(
            headers: headers,
            body: body
        ))
    }
    /// Transcribe (Pre-recorded)
    ///
    /// Transcribe an audio file. The model is chosen via `?model=`:
    ///
    /// - `?model=pulse-pro`: English-only, leaderboard-ranked accuracy. Raw bytes only; pass `webhook_url` to receive transcription asynchronously on long files.
    /// - `?model=pulse`: multilingual transcription (21 streaming + 12 pre-recorded languages), supports both raw bytes and audio-by-URL.
    ///
    /// ## When to use this
    ///
    /// Use this endpoint when you have a complete audio file (call recording, voicemail, podcast episode) and want the transcript back in one response. For live transcription as audio arrives, use the realtime WebSocket endpoint (`WS /waves/v1/stt/live?model=pulse`).
    ///
    /// Pulse Pro is HTTP-only.
    ///
    /// ## Input methods
    ///
    /// - **Raw bytes**: `Content-Type: application/octet-stream` with the audio in the body. All knobs are query parameters.
    /// - **URL (`?model=pulse` only)**: `Content-Type: application/json` with `{"url": "..."}` in the body.
    ///
    /// ## Examples
    ///
    /// **cURL**: Pulse Pro, sync
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/stt/?model=pulse-pro&language=en&word_timestamps=true" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/octet-stream" \
    ///   --data-binary "@./call.wav"
    /// ```
    ///
    /// **cURL**: Pulse Pro, async via webhook
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/stt/?model=pulse-pro&language=en&webhook_url=https://your.app/cb" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/octet-stream" \
    ///   --data-binary "@./call.wav"
    /// ```
    /// Returns `200 { "status": "processing", "request_id": "..." }` immediately. The webhook receives the full transcription when ready.
    ///
    /// **cURL**: Pulse, audio-by-URL
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/stt/?model=pulse&language=en" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -d '{"url": "https://your-bucket.s3.amazonaws.com/call.wav"}'
    /// ```
    ///
    /// **Python**
    /// ```python
    /// import requests
    ///
    /// with open("./call.wav", "rb") as f:
    ///     audio = f.read()
    ///
    /// r = requests.post(
    ///     "https://api.smallest.ai/waves/v1/stt/",
    ///     params={"model": "pulse-pro", "language": "en", "word_timestamps": "true"},
    ///     headers={"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/octet-stream"},
    ///     data=audio,
    /// )
    /// r.raise_for_status()
    /// print(r.json()["transcription"])
    /// ```
    ///
    /// **JavaScript / TypeScript**
    /// ```typescript
    /// import { readFileSync } from "node:fs";
    ///
    /// const audio = readFileSync("./call.wav");
    /// const params = new URLSearchParams({ model: "pulse-pro", language: "en", word_timestamps: "true" });
    ///
    /// const res = await fetch(`https://api.smallest.ai/waves/v1/stt/?${params}`, {
    ///   method: "POST",
    ///   headers: { Authorization: `Bearer ${process.env.SMALLEST_API_KEY}`, "Content-Type": "application/octet-stream" },
    ///   body: audio,
    /// });
    /// console.log((await res.json()).transcription);
    /// ```
    ///
    /// ## Common gotchas
    ///
    /// - **`model` is required.** Missing or invalid values return `400` with an enum-validation error.
    /// - **Pulse Pro is English only.** Pass `language=en`. Any other value returns `400 invalid_enum_value` (`Expected 'en', received '<x>'`).
    /// - **Pulse Pro does not support audio-by-URL.** Send raw bytes or use `?model=pulse` for the URL flow.
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/stt/`.
    /// - Remark: Generated from `#/paths//waves/v1/stt//post(speechToText_transcribe)`.
    public func speechToText_transcribe(
        query: Operations.speechToText_transcribe.Input.Query,
        headers: Operations.speechToText_transcribe.Input.Headers = .init(),
        body: Operations.speechToText_transcribe.Input.Body? = nil
    ) async throws -> Operations.speechToText_transcribe.Output {
        try await speechToText_transcribe(Operations.speechToText_transcribe.Input(
            query: query,
            headers: headers,
            body: body
        ))
    }
    /// Chat Completions (Electron)
    ///
    /// Generate a chat completion with Electron. OpenAI-compatible
    /// request/response shape — point any OpenAI SDK at
    /// `https://api.smallest.ai/waves/v1` and it just works.
    ///
    /// Set `stream: true` to receive tokens via Server-Sent Events. With
    /// `stream_options: { include_usage: true }`, the final SSE chunk
    /// carries the `usage` block so token accounting is exact even on
    /// client disconnects.
    ///
    /// Tool calling follows OpenAI's `tools` array convention. When you
    /// provide a voice-agent-style system prompt, Electron emits a short
    /// filler phrase in the assistant message `content` field alongside
    /// `tool_calls` — see the [Tool Calling guide](/models/llm/tool-function-calling)
    /// for the voice-agent pattern.
    ///
    /// ## Examples
    ///
    /// **cURL**
    /// ```bash
    /// curl -X POST "https://api.smallest.ai/waves/v1/chat/completions" \
    ///   -H "Authorization: Bearer $SMALLEST_API_KEY" \
    ///   -H "Content-Type: application/json" \
    ///   -d '{
    ///     "model": "electron",
    ///     "messages": [
    ///       {"role": "user", "content": "Write one sentence about why the sky is blue."}
    ///     ]
    ///   }'
    /// ```
    ///
    /// **Python** (`pip install openai`)
    /// ```python
    /// import os
    /// from openai import OpenAI
    ///
    /// client = OpenAI(
    ///     base_url="https://api.smallest.ai/waves/v1",
    ///     api_key=os.environ["SMALLEST_API_KEY"],
    /// )
    ///
    /// response = client.chat.completions.create(
    ///     model="electron",
    ///     messages=[
    ///         {"role": "user", "content": "Write one sentence about why the sky is blue."}
    ///     ],
    /// )
    ///
    /// print(response.choices[0].message.content)
    /// ```
    ///
    /// **JavaScript / TypeScript** (`npm install openai`)
    /// ```typescript
    /// import OpenAI from "openai";
    ///
    /// const client = new OpenAI({
    ///   baseURL: "https://api.smallest.ai/waves/v1",
    ///   apiKey: process.env.SMALLEST_API_KEY,
    /// });
    ///
    /// const response = await client.chat.completions.create({
    ///   model: "electron",
    ///   messages: [
    ///     { role: "user", content: "Write one sentence about why the sky is blue." },
    ///   ],
    /// });
    ///
    /// console.log(response.choices[0].message.content);
    /// ```
    ///
    /// **Streaming with usage** (Python)
    /// ```python
    /// stream = client.chat.completions.create(
    ///     model="electron",
    ///     messages=[{"role": "user", "content": "Tell me a one-sentence fun fact."}],
    ///     stream=True,
    ///     stream_options={"include_usage": True},
    /// )
    /// for chunk in stream:
    ///     if chunk.choices and chunk.choices[0].delta.content:
    ///         print(chunk.choices[0].delta.content, end="", flush=True)
    ///     if chunk.usage:
    ///         print(f"\n\nTokens: {chunk.usage.total_tokens}")
    /// ```
    ///
    /// ## Common gotchas
    ///
    /// - **Base URL is `/waves/v1`**, not `/v1`. The OpenAI SDK appends `/chat/completions` for you.
    /// - **`stream_options.include_usage: true`** is required for exact token accounting on streaming calls — the final SSE chunk carries the `usage` block.
    /// - **`n > 1` and `prompt_logprobs` are rejected.** Use multiple requests if you need parallel completions.
    /// - **Auth header is `Authorization: Bearer $SMALLEST_API_KEY`** — get the key from the [Smallest AI Console](https://app.smallest.ai/dashboard/api-keys).
    ///
    ///
    /// - Remark: HTTP `POST /waves/v1/chat/completions`.
    /// - Remark: Generated from `#/paths//waves/v1/chat/completions/post(electron_complete)`.
    public func electron_complete(
        headers: Operations.electron_complete.Input.Headers = .init(),
        body: Operations.electron_complete.Input.Body? = nil
    ) async throws -> Operations.electron_complete.Output {
        try await electron_complete(Operations.electron_complete.Input(
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    /// waves
    public enum Server1 {
        /// waves
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://api.smallest.ai",
                variables: []
            )
        }
    }
    /// waves
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://api.smallest.ai",
            variables: []
        )
    }
}
