// Auto-generated by swift-openapi-bootstrapper

import Foundation
import Testing
import SmallestAIAPI
import SmallestAIAPITypes
import OpenAPIAsyncHTTPClient
import OpenAPIRuntime
import UsefulThings

struct SmallestAIAPITests {
    private static let packageDirectory = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()

    private static var apiKey: String? {
        guard let value = UsefulThings.getEnvironmentVariable(
            "API_KEY", from: packageDirectory.appendingPathComponent(".env")
        ) else { return nil }
        let key = value.trimmingCharacters(in: .whitespacesAndNewlines)
        return key.isEmpty || key == "your_api_key_here" ? nil : key
    }

    // Sends a real, billable request when API_KEY is set in the environment or .env.
    @Test(
        "Transcribe 60s_speech.wav with the live Waves API",
        .enabled(if: apiKey != nil, "Set API_KEY in the environment or the package's .env file")
    )
    func transcribeSpeechFile() async throws {
        let apiKey = try #require(Self.apiKey)
        let audioURL = Self.packageDirectory.appendingPathComponent("60s_speech.wav")
        let file = try FileHandle(forReadingFrom: audioURL)
        defer { try? file.close() }

        let byteCount = try file.seekToEnd()
        try file.seek(toOffset: 0)
        #expect(byteCount > 0)

        // UsefulThings makes FileHandle an AsyncSequence of byte chunks.
        let body = HTTPBody(file, length: .known(Int64(byteCount)), iterationBehavior: .single)
        let client = Client(
            serverURL: try Servers.Server1.url(),
            transport: AsyncHTTPClientTransport(configuration: .init(timeout: .seconds(120))),
            middlewares: [AuthenticationMiddleware(apiKey: "Bearer \(apiKey)")]
        )
        let input = Operations.speechToText_transcribe.Input(
            query: .init(model: .pulse_hyphen_pro, language: .en),
            body: .binary(body)
        )
        let response = try await client.speechToText_transcribe(input)
        let payload = try response.ok.body.json
        guard case let .TranscriptionResponse(transcription) = payload else {
            Issue.record("Expected a synchronous transcription, received \(payload)")
            return
        }
        #expect(!transcription.transcription.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
        print("Transcription: \(transcription.transcription)")
    }
}
